### ISSUE TITLE
修改主题颜色时接收区功能会被拉长

### ISSUE THREAD

**Issue by kksdtty** [nixgnauhcuy/QtComMate#1]
如下图：
![1](https://github.com/nixgnauhcuy/QtComMate/assets/137848271/2314ea42-534d-4d83-8f3d-a6b047efb1d5)
![2](https://github.com/nixgnauhcuy/QtComMate/assets/137848271/100d7245-e15a-4d70-b200-72771a44adcf)

**Comment by nixgnauhcuy** [comment]
https://github.com/nixgnauhcuy/QtComMate/commit/4cccf0cf7926cb6aa373f0b4b69068ac8eefac0d
