### ISSUE TITLE
发送hex数据有问题

### ISSUE THREAD

**Issue by cc-caixf** [nixgnauhcuy/QtComMate#2]
[这里](https://github.com/nixgnauhcuy/QtComMate/blob/4cccf0cf7926cb6aa373f0b4b69068ac8eefac0d/src/main.py#L292)

应该改成:

`data = bytes.fromhex(hex_string)`

**Comment by nixgnauhcuy** [comment]
@cc-caixf 我这边看了下，发送 hex 数据到串口工具数据正常，能确定下你的复现路径和发送的错误数据吗？

**Comment by cc-caixf** [comment]
串口工具短接, 发送16进制数据(异常收发):
![image](https://github.com/nixgnauhcuy/QtComMate/assets/19278194/820673ce-6b69-4d95-8896-fbc7641b127e)
另一款工具(正常收发):
![image](https://github.com/nixgnauhcuy/QtComMate/assets/19278194/0fa71ad1-6470-4b5b-95c2-6612d9dbca2d)

测试中, 发现了另一个问题: 如果串口connect状态下关闭软件, 软件不会释放串口, 再开软件(或者用别的串口工具)不能正常connect.  然后 任务管理器 里显示进程还在....
![image](https://github.com/nixgnauhcuy/QtComMate/assets/19278194/eb10182f-c06f-4407-a6df-e16bc5de77c1)

**Comment by cc-caixf** [comment]
再补充个问题:
(不知道是否与关闭软件之前有没有disconnect串口相关)
软件已经关闭, 但是 任务管理器 里的进程还在....
![image](https://github.com/nixgnauhcuy/QtComMate/assets/19278194/eb10182f-c06f-4407-a6df-e16bc5de77c1)

**Comment by nixgnauhcuy** [comment]
@cc-caixf 
- [716d99b87eab52b200b9474e972da9011c45612a](https://github.com/nixgnauhcuy/QtComMate/commit/716d99b87eab52b200b9474e972da9011c45612a)
- [f88fcc6deeff01f065b638fb4da1278d8027c983](https://github.com/nixgnauhcuy/QtComMate/commit/f88fcc6deeff01f065b638fb4da1278d8027c983)

十六进制发送异常和资源未释放的问题，我修改了，可以验证下

**Comment by nixgnauhcuy** [comment]
效果可以参考这个，https://www.z4a.net/image/test.VqwJDf
可以自己打包下，打包方式可以参考 https://www.nixgnauhcuy.cn/cc72c04a110b/

**Comment by cc-caixf** [comment]
嗯, 测试可以

**Comment by cc-caixf** [comment]
这个串口connet后, 不收发数据也特别占用cpu资源, 是别的串口工具的3~5倍数(比如别的串口工具是7%,  这个要到20%~40%)

**Comment by nixgnauhcuy** [comment]
@cc-caixf  已修复：
- [a2c5e793d7a18046482ceecb7f8f6bd6a8638d2f](https://github.com/nixgnauhcuy/QtComMate/commit/a2c5e793d7a18046482ceecb7f8f6bd6a8638d2f)

**Comment by cc-caixf** [comment]
这种改法不太优雅, 
既然用了queue, 那就直接用queue来阻塞read线程就行了, 
[这里](https://github.com/nixgnauhcuy/QtComMate/blob/a2c5e793d7a18046482ceecb7f8f6bd6a8638d2f/src/serialport.py#L116) 改成:
```python
    def read(self):
        return self.receiveQueue.get(True)
```

**Comment by nixgnauhcuy** [comment]
串口连接后会开启三个线程，串口收发各分配了一个，分别是 `SerialPortReceiveThread` 和 `SerialPortSendThread`，它们都执行了 while(1) 来等待串口数据和填充队列，导致了线程使用的cpu高，用 sleep 可以在没有数据可用的时候让线程休息，我尝试了你的方式，并不能有效的降低cpu的使用频率，可以测试下。

**Comment by cc-caixf** [comment]
我测试了的, 是可行的. 
![image](https://github.com/nixgnauhcuy/QtComMate/assets/19278194/6431796c-9eb2-4687-a3a2-f89931a71ab1)

**Comment by nixgnauhcuy** [comment]
我这边重新验证了下，

这个截图，使用的是你的方法，
![0](https://github.com/nixgnauhcuy/QtComMate/assets/73231354/5e07775b-a733-41dc-a700-5a6cc1296846)

这个是目前提交的方法，
![1](https://github.com/nixgnauhcuy/QtComMate/assets/73231354/db0487be-7a9c-468b-b5b4-74e1a2dcf5af)

我将两种方式都进行了打包测试，差异还是存在
![3](https://github.com/nixgnauhcuy/QtComMate/assets/73231354/3df7ebc8-7985-4a4e-b580-58e0809769b2)

**Comment by nixgnauhcuy** [comment]
也许你可以提交 pr，我确信你的方式是有效的，但是不使用下述提交，不会很显著的降低 CPU
- [a2c5e793d7a18046482ceecb7f8f6bd6a8638d2f](https://github.com/nixgnauhcuy/QtComMate/commit/a2c5e793d7a18046482ceecb7f8f6bd6a8638d2f)

**Comment by cc-caixf** [comment]
其它地方的代码没动, 可以将 `serialport.py` 简化成如下:
```python
import serial
import time


class SerialPort(object):
    def __init__(self) -> None:
        self.serial = None

    def open(self, port, baudrate, databit, checkbit, stopbit, xonxoff, rtscts, dsrdtr) -> bool:
        if self.serial is None:
            try:
                self.serial = serial.Serial(port, baudrate, databit, checkbit, stopbit, 0.1, xonxoff, rtscts, 0, dsrdtr)
            except Exception as e:
                print(e)
                return False
            self.oneByteInter = (databit + 2 + (0 if checkbit == "N" else 1)) / baudrate * 2
            return True

    def close(self) -> bool:
        if self.serial is not None:
            self.serial.close()
            self.serial = None
            return True
        return False

    def isOpen(self) -> bool:
        if self.serial is None:
            return False
        else:
            return True

    def write(self, data: bytes) -> None:
        if self.serial is not None:
            self.serial.write(data)

    def read(self) -> bytes:
        if self.serial is not None:
            data = b""
            while True:
                nums = max(1, self.serial.in_waiting)
                d = self.serial.read(nums)

                if d:
                    data += d
                    t = time.time()
                if data and time.time() - t > self.oneByteInter:
                    break

            return data
```
其中`read`函数参考了[这里](https://github.com/Neutree/COMTool/blob/943869d6f180076a84637c04d8385654872339a5/COMTool/conn/conn_serial.py#L444)

然后, 
- 在没有connect的状态下, 在输入文本框中输入字符, 点发送,, 右下角S的值会增加, 应该是哪里没加判断... 
- 当接收窗口显示满后, 接收到的最新一行需要将滚轮向下滑动才能显示出来

**Comment by nixgnauhcuy** [comment]
我合并了部分代码，
- 更改了串口写接口，定时 1ms 压力测试下，不会有数据丢失的情况。
- 增加了接口的 type hinting，这可以提高对代码的可读性。

但是对于 `read` 部分还存在一些问题，我尝试在定时发送给串口工具大量数据时，界面数据更新卡顿，或许你那边可以验证下，对于新的两个bug，我会抽空验证下，谢谢。

**Comment by cc-caixf** [comment]
`界面数据更新卡顿` 是指一直在接收, 接收窗口里数据没有显示出来吗(不是界面没反应, 界面卡顿住的话, 那是另外一个问题)? 这个我想是正常的吧, 别的软件里, 发送方如果一直在发, 软件(接收方)就会一直在接收(粘包) (**但是R值会有变化, 提示一直在接受**), 需要发送方暂停一个小间隔时间, 软件(接收方)才判断发送方发送完成, 将一个帧完整显示出来.
- 然后, 这个hex发送接收的 R 值不对, 我发送2个字节, 收到却有6个字节
![image](https://github.com/nixgnauhcuy/QtComMate/assets/19278194/4dfbad62-bb25-49e5-a0e6-193d4ae7a883)

**Comment by nixgnauhcuy** [comment]
可能是我描述的不对,可以参考这个[链接](https://go.wetransfer.com/t-CXS2gpoqCQ)视频的对比.

**Comment by cc-caixf** [comment]
是一个东西, 我描述的是一种实现方式, 你对比视频里的是另一种实现方式(视频里的实现方式更好)

**Comment by nixgnauhcuy** [comment]
所以从我目前的体验上来看,目前 `read` 的方式还不需要更改

**Comment by nixgnauhcuy** [comment]
针对反馈的问题，修复如下：
- **在没有 connect 的状态下，在输入文本框中输入字符，点发送，，右下角 S 的值会增加，应该是哪里没加判断...**，
   - [2796e41e5d16e0007834e8d03878db323157f85e](https://github.com/nixgnauhcuy/QtComMate/commit/2796e41e5d16e0007834e8d03878db323157f85e)
- **hex 发送接收的 R 值不对，我发送 2 个字节，收到却有 6 个字节**
   - [36633e37bcd31fa7957da6d23312cc65d724af42](https://github.com/nixgnauhcuy/QtComMate/commit/36633e37bcd31fa7957da6d23312cc65d724af42)
- **当接收窗口显示满后，接收到的最新一行需要将滚轮向下滑动才能显示出来**
   - 未复现，无需修复

**Comment by cc-caixf** [comment]
我按你视频里的示例实现了一个版本, 在我仓库里, 可以参考. 
补充(那个read应该改成下面这样, 不然又cpu爆炸):
```python
    def read(self) -> bytes:
        if self.serial is not None:
            num = max(1, self.serial.inWaiting())
            return self.serial.read(num)
        return bytes()
```
![动画 ](https://github.com/nixgnauhcuy/QtComMate/assets/19278194/b4586099-e3fc-450c-92b2-23466f71bf60)

然后, 从gif里面也可以看到 `接收到的最新一行需要将滚轮向下滑动才能显示出来` 这个问题

**Comment by nixgnauhcuy** [comment]
好的，这个 **接收到的最新一行需要将滚轮向下滑动才能显示出来** 问题确实存在，我暂时没有好的方法可以解决它，不过这个问题不是特别严重，我会持续关注这个问题。
另外我留意到你将 `self.dataReceivedSignal.emit(data.decode("iso-8859-1"), dataLen)` 更改为 `self.dataReceivedSignal.emit(data.decode('utf-8'), dataLen)`，改修改会导致，在发送非 utf-8 范围的数据时(例如0x96)，会提示` 'utf-8' codec can't decode byte 0x96 in position 0: invalid start byte`.
还有目前的 `read` 方式，我尝试了下，它并不能通过压力测试，它在高数据量时体现不是很好，卡顿明显并且会丢失数据，这是串口工具不应该存在的问题，我将对比的视频发到你 github 公开的邮箱了，请查收，我不确定你是否可以收到邮件，如果不能请告知我。

**Comment by nixgnauhcuy** [comment]
我对新修改的发送进行了测试，同样是在高数据发送下，会导致数据丢失，并且数据发送接口不断输出数据。

**Comment by cc-caixf** [comment]
对比视频看到了. 
- 非hex的情况出现0x96, 我想是不是 提示 勾选hex 会好一点
- 掉数据, 是底层的buffer溢出了应该
然后针对卡住界面的情况, 改了下代码
![动画 ](https://github.com/nixgnauhcuy/QtComMate/assets/19278194/7e2b4599-109c-4869-be7b-adf03bedaf40)

然后别的工具的策略: 实时更新R值, 接收到的内容延后更新: 
![动画 ](https://github.com/nixgnauhcuy/QtComMate/assets/19278194/1fe4d589-2fa9-4311-b697-b341a6e89793)

然后 滚轮的问题, [这里](https://github.com/nixgnauhcuy/QtComMate/blob/130f8a20c479e76cfede8e3d26dc65766d86dd15/src/main.py#L268C5-L268C5) 改成(2句语句顺序换一下):
```pythan
self.SerialReceivePlainTextEdit.insertPlainText(timestamp+data)
self.SerialReceivePlainTextEdit.moveCursor(QTextCursor.MoveOperation.End)
```

**Comment by cc-caixf** [comment]
> 我对新修改的发送进行了测试，同样是在高数据发送下，会导致数据丢失，并且数据发送接口不断输出数据。

![image](https://github.com/nixgnauhcuy/QtComMate/assets/19278194/5d2af40c-6fca-4263-a0c8-d4e4f79b5af7)

我测了一下, 用1200bps, 10ms间隔发送, 可以看到接收的数据量是跟发送的数据量一致的

可能你是直接点了disconnect, 而我是将10ms前的勾去掉, 因为是异步发送的, 直接disconnect的话, 会导致后面的数据没有发送, 而S值已经增加了, 这里是有点问题

**Comment by nixgnauhcuy** [comment]
- 滚轮问题依旧存在，可以反复验证下
- 对于**实时更新 R 值，接收到的内容延后更新**，这个策略对于我来说是不能接受的，目前接触的大部分工具都是实时展示数据的。

**Comment by cc-caixf** [comment]
你指的是最后一行的空白行吗? 
问了下chatgpt, 那个是 `QPlainTextEdit ` 控件的`输入行`, 如果不要该输入行, 要么重写控件, 要么用`QTextEdit` 控件替换, 下面是两种控件的对比
![动画 ](https://github.com/nixgnauhcuy/QtComMate/assets/19278194/d40521e7-fa57-44a8-9acd-2d021afd7efb)
![动画 1](https://github.com/nixgnauhcuy/QtComMate/assets/19278194/1905707e-790d-4571-819e-b78eeb76649d)

**Comment by nixgnauhcuy** [comment]
我的意思是，它有时候不需要滚动就是最后一行，有时候需要滚动一行，所以我不清楚它是什么情况导致的。`QPlainTextEdit`和`QTextEdit` 之前设计的时候有纠结过，不过我忘记了是什么原因让我选择使用了`QPlainTextEdit`。
![test](https://github.com/nixgnauhcuy/QtComMate/assets/73231354/5504149c-a230-45c3-80a1-1ed0fba677bf)
